version: 1.0.{build}
configuration: Debug
environment:
  testspace_token:
    secure: eYdBAucoce5nKfWjWvBIXyf/1pZkZgNId9tz5YYLSQeujGugPzpP6XnHeFBkm6fb
install:
- ps: >-
    mkdir .\money\packages

    mkdir .\money\packages\testspace

    wget https://testspace-runner.s3.amazonaws.com/testspace-windows-latest.zip -outfile .\money\packages\testspace.zip

    7z x .\money\packages\testspace.zip -omoney\packages\testspace
before_build:
- cmd: nuget restore money/cs-money.sln
build:
  project: money/cs-money.sln
  verbosity: minimal
test_script:
- ps: >-
    .\money\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:".\money\packages\NUnit.ConsoleRunner.3.2.1\tools\nunit3-console.exe" -targetargs:'.\money\bin\Debug\cs-money.dll' -register:user


    .\money\packages\testspace\testspace.exe publish .\results.xml .\testresult.xml ${ENV:testspace_token}:@jschultz.testspace.com/my-project/Nunit
on_finish:
- ps: 